// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftwareTracker.Data;

#nullable disable

namespace SoftwareTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoftwareTracker.Models.LicensePurchase", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("LicenseKey").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<int>("LicenseType").HasColumnType("int");
                b.Property<string>("Notes").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<string>("OrderNumber").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime>("PurchaseDate").HasColumnType("datetime2");
                b.Property<int>("Quantity").HasColumnType("int");
                b.Property<int>("SoftwareTitleId").HasColumnType("int");
                b.Property<decimal?>("UnitCost").HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.HasIndex("SoftwareTitleId");
                b.ToTable("LicensePurchases");
            });

            modelBuilder.Entity("SoftwareTracker.Models.MaintenanceContract", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<decimal?>("AnnualCost").HasColumnType("decimal(18,2)");
                b.Property<string>("ContactEmail").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("ContactPhone").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("ContractNumber").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime>("EndDate").HasColumnType("datetime2");
                b.Property<int>("LicensePurchaseId").HasColumnType("int");
                b.Property<string>("Notes").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<DateTime>("StartDate").HasColumnType("datetime2");
                b.Property<string>("VendorContact").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.HasKey("Id");
                b.HasIndex("LicensePurchaseId");
                b.ToTable("MaintenanceContracts");
            });

            modelBuilder.Entity("SoftwareTracker.Models.SoftwareTitle", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Category").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Description").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Vendor").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Website").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.HasKey("Id");
                b.ToTable("SoftwareTitles");
            });

            modelBuilder.Entity("SoftwareTracker.Models.Subscription", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<bool>("AutoRenews").HasColumnType("bit");
                b.Property<int>("BillingPeriod").HasColumnType("int");
                b.Property<decimal?>("CostPerPeriod").HasColumnType("decimal(18,2)");
                b.Property<DateTime>("EndDate").HasColumnType("datetime2");
                b.Property<string>("Notes").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<int?>("SeatCount").HasColumnType("int");
                b.Property<int>("SoftwareTitleId").HasColumnType("int");
                b.Property<DateTime>("StartDate").HasColumnType("datetime2");
                b.Property<string>("SubscriptionReference").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.HasKey("Id");
                b.HasIndex("SoftwareTitleId");
                b.ToTable("Subscriptions");
            });

            modelBuilder.Entity("SoftwareTracker.Models.LicensePurchase", b =>
            {
                b.HasOne("SoftwareTracker.Models.SoftwareTitle", "SoftwareTitle")
                    .WithMany("LicensePurchases")
                    .HasForeignKey("SoftwareTitleId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("SoftwareTitle");
            });

            modelBuilder.Entity("SoftwareTracker.Models.MaintenanceContract", b =>
            {
                b.HasOne("SoftwareTracker.Models.LicensePurchase", "LicensePurchase")
                    .WithMany("MaintenanceContracts")
                    .HasForeignKey("LicensePurchaseId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("LicensePurchase");
            });

            modelBuilder.Entity("SoftwareTracker.Models.Subscription", b =>
            {
                b.HasOne("SoftwareTracker.Models.SoftwareTitle", "SoftwareTitle")
                    .WithMany("Subscriptions")
                    .HasForeignKey("SoftwareTitleId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("SoftwareTitle");
            });

            modelBuilder.Entity("SoftwareTracker.Models.LicensePurchase", b =>
            {
                b.Navigation("MaintenanceContracts");
            });

            modelBuilder.Entity("SoftwareTracker.Models.SoftwareTitle", b =>
            {
                b.Navigation("LicensePurchases");
                b.Navigation("Subscriptions");
            });
#pragma warning restore 612, 618
        }
    }
}
